### ISSUE TITLE
DateTime objects cause panics at certain times of day

### ISSUE THREAD

**Issue by Azy8BsKXVko** [lifthrasiir/rust-chrono#72]
I'm not sure if this is chrono, or something *I'm* doing wrong, but an application I'm writing with the following code produces a panic at only certain times of day:

```rust
let format = arguments.value_of("format").unwrap_or("%H%d%m%Y");

let temp: i32 = Local::now().format(format).to_string().parse().unwrap();
```

I've noticed this in the evening, around 22:00. It produces this panic:

```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: Overflow }', ../src/libcore/result.rs:746
```

To try and figure out what was going on, I replaced the second line of code with

```rust
let temp: i32 = UTC.ymd(2016, 4, 21).and_hms(22, 0, 0).format(format).to_string().parse().unwrap();
```

and changed the 22 to various reasonable integers. It will always panic at 22, and sometimes panic at 20 and 21. It panicked at 23 when I tested it just now, but that was just once. It doesn't seem to panic at any other time, but more vigorous testing may prove otherwise.

**Comment by lifthrasiir** [comment]
`parse` is a generic method ultimately implemented by [`FromStr` trait](https://doc.rust-lang.org/std/str/trait.FromStr.html) which is implemented for many types including `i32`. The `to_string` call results in a 10-digit number starting with `22`, that is out of bounds (the maximum value of `i32` is about 21 4700 0000).

In order to parse your own format into the `DateTime` value, you need to use `Offset::datetime_from_str` method (as you lack the time zone offset):

```rust
let a = UTC.ymd(2016, 4, 21).and_hms(22, 0, 0).format("%H%d%m%Y").to_string();
println!("{:?}", a);
let b = UTC.datetime_from_str(&a, "%H%d%m%Y");
println!("{:?}", b);
```

...except that it does not work; it simply returns `Err(ParseError(NotEnough))` because it cannot determine the exact date and time without minutes. There are some workarounds, but probably the simplest way is to put a dummy field:

```rust
let b = UTC.datetime_from_str(&(a + "00"), "%H%d%m%Y%M");
println!("{:?}", b);
```

Now it correctly returns `Ok(2016-04-21T22:00:00Z)`.

**Comment by Azy8BsKXVko** [comment]
Thank you.
